use {
    self::video::VideoAPI,
    crate::{
        ctypes::{c_char, c_void},
        define_crankstart_api, playdate_graphics, LCDBitmap, LCDBitmapDrawMode, LCDBitmapFlip,
        LCDBitmapTable, LCDColor, LCDFont, LCDFontData, LCDFontGlyph, LCDFontPage, LCDLineCapStyle,
        LCDPolygonFillRule, LCDRect, LCDSolidColor, PDStringEncoding,
    },
};

pub mod video;

define_crankstart_api! {
    #[allow(dead_code)]
    pub(crate) struct GraphicsAPI => playdate_graphics {
        pub video: VideoAPI;
        pub clear: unsafe extern "C" fn(color: LCDColor),
        pub setBackgroundColor: unsafe extern "C" fn(color: LCDSolidColor),
        pub setStencil: unsafe extern "C" fn(stencil: *mut LCDBitmap),
        pub setDrawMode: unsafe extern "C" fn(mode: LCDBitmapDrawMode) -> LCDBitmapDrawMode,
        pub setDrawOffset: unsafe extern "C" fn(dx: i32, dy: i32),
        pub setClipRect: unsafe extern "C" fn(x: i32, y: i32, width: i32, height: i32),
        pub clearClipRect: unsafe extern "C" fn(),
        pub setLineCapStyle: unsafe extern "C" fn(endCapStyle: LCDLineCapStyle),
        pub setFont: unsafe extern "C" fn(font: *mut LCDFont),
        pub setTextTracking: unsafe extern "C" fn(tracking: i32),
        pub pushContext: unsafe extern "C" fn(target: *mut LCDBitmap),
        pub popContext: unsafe extern "C" fn(),
        pub drawBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
            flip: LCDBitmapFlip,
        ),
        pub tileBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            flip: LCDBitmapFlip,
        ),
        pub drawLine: unsafe extern "C" fn(
            x1: i32,
            y1: i32,
            x2: i32,
            y2: i32,
            width: i32,
            color: LCDColor,
        ),
        pub fillTriangle: unsafe extern "C" fn(
            x1: i32,
            y1: i32,
            x2: i32,
            y2: i32,
            x3: i32,
            y3: i32,
            color: LCDColor,
        ),
        pub drawRect: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            color: LCDColor,
        ),
        pub fillRect: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            color: LCDColor,
        ),
        pub drawEllipse: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            lineWidth: i32,
            startAngle: f32,
            endAngle: f32,
            color: LCDColor,
        ),
        pub fillEllipse: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            startAngle: f32,
            endAngle: f32,
            color: LCDColor,
        ),
        pub drawScaledBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
            xscale: f32,
            yscale: f32,
        ),
        pub drawText: unsafe extern "C" fn(
            text: *const c_void,
            len: usize,
            encoding: PDStringEncoding,
            x: i32,
            y: i32,
        ) -> i32,
        pub newBitmap: unsafe extern "C" fn(
            width: i32,
            height: i32,
            bgcolor: LCDColor,
        ) -> *mut LCDBitmap,
        pub freeBitmap: unsafe extern "C" fn(arg1: *mut LCDBitmap),
        pub loadBitmap: unsafe extern "C" fn(
            path: *const c_char,
            outerr: *mut *const c_char,
        ) -> *mut LCDBitmap,
        pub copyBitmap: unsafe extern "C" fn(bitmap: *mut LCDBitmap) -> *mut LCDBitmap,
        pub loadIntoBitmap: unsafe extern "C" fn(
            path: *const c_char,
            bitmap: *mut LCDBitmap,
            outerr: *mut *const c_char,
        ),
        pub getBitmapData: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            width: *mut i32,
            height: *mut i32,
            rowbytes: *mut i32,
            mask: *mut *mut u8,
            data: *mut *mut u8,
        ),
        pub clearBitmap: unsafe extern "C" fn(bitmap: *mut LCDBitmap, bgcolor: LCDColor),
        pub rotatedBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            rotation: f32,
            xscale: f32,
            yscale: f32,
            allocedSize: *mut i32,
        ) -> *mut LCDBitmap,
        pub newBitmapTable: unsafe extern "C" fn(
            count: i32,
            width: i32,
            height: i32,
        ) -> *mut LCDBitmapTable,
        pub freeBitmapTable: unsafe extern "C" fn(table: *mut LCDBitmapTable),
        pub loadBitmapTable: unsafe extern "C" fn(
            path: *const c_char,
            outerr: *mut *const c_char,
        ) -> *mut LCDBitmapTable,
        pub loadIntoBitmapTable: unsafe extern "C" fn(
            path: *const c_char,
            table: *mut LCDBitmapTable,
            outerr: *mut *const c_char,
        ),
        pub getTableBitmap:
            unsafe extern "C" fn(table: *mut LCDBitmapTable, idx: i32) -> *mut LCDBitmap,
        pub loadFont: unsafe extern "C" fn(
            path: *const c_char,
            outErr: *mut *const c_char,
        ) -> *mut LCDFont,
        pub getFontPage: unsafe extern "C" fn(font: *mut LCDFont, c: u32) -> *mut LCDFontPage,
        pub getPageGlyph: unsafe extern "C" fn(
            page: *mut LCDFontPage,
            c: u32,
            bitmap: *mut *mut LCDBitmap,
            advance: *mut i32,
        ) -> *mut LCDFontGlyph,
        pub getGlyphKerning: unsafe extern "C" fn(
            glyph: *mut LCDFontGlyph,
            glyphcode: u32,
            nextcode: u32,
        ) -> i32,
        pub getTextWidth: unsafe extern "C" fn(
            font: *mut LCDFont,
            text: *const c_void,
            len: usize,
            encoding: PDStringEncoding,
            tracking: i32,
        ) -> i32,
        pub getFrame: unsafe extern "C" fn() -> *mut u8,
        pub getDisplayFrame: unsafe extern "C" fn() -> *mut u8,
        pub getDebugBitmap: unsafe extern "C" fn() -> *mut LCDBitmap,
        pub copyFrameBufferBitmap: unsafe extern "C" fn() -> *mut LCDBitmap,
        pub markUpdatedRows: unsafe extern "C" fn(start: i32, end: i32),
        pub display: unsafe extern "C" fn(),
        pub setColorToPattern: unsafe extern "C" fn(
            color: *mut LCDColor,
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
        ),
        pub checkMaskCollision: unsafe extern "C" fn(
            bitmap1: *mut LCDBitmap,
            x1: i32,
            y1: i32,
            flip1: LCDBitmapFlip,
            bitmap2: *mut LCDBitmap,
            x2: i32,
            y2: i32,
            flip2: LCDBitmapFlip,
            rect: LCDRect,
        ) -> i32,
        pub setScreenClipRect: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
        ),
        pub fillPolygon: unsafe extern "C" fn(
            nPoints: i32,
            coords: *mut i32,
            color: LCDColor,
            fillrule: LCDPolygonFillRule,
        ),
        pub getFontHeight: unsafe extern "C" fn(font: *mut LCDFont) -> u8,
        pub getDisplayBufferBitmap: unsafe extern "C" fn() -> *mut LCDBitmap,
        pub drawRotatedBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
            rotation: f32,
            centerx: f32,
            centery: f32,
            xscale: f32,
            yscale: f32,
        ),
        pub setTextLeading: unsafe extern "C" fn(lineHeightAdustment: i32),
        pub setBitmapMask:
            unsafe extern "C" fn(bitmap: *mut LCDBitmap, mask: *mut LCDBitmap) -> i32,
        pub getBitmapMask: unsafe extern "C" fn(bitmap: *mut LCDBitmap) -> *mut LCDBitmap,
        pub setStencilImage: unsafe extern "C" fn(stencil: *mut LCDBitmap, tile: i32),
        pub makeFontFromData:
            unsafe extern "C" fn(data: *mut LCDFontData, wide: i32) -> *mut LCDFont,
        pub getTextTracking: unsafe extern "C" fn() -> i32,
        pub setPixel: unsafe extern "C" fn(x: i32, y: i32, c: LCDColor),
        pub getBitmapPixel: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
        ) -> LCDSolidColor,
        pub getBitmapTableInfo: unsafe extern "C" fn(
            table: *mut LCDBitmapTable,
            count: *mut i32,
            width: *mut i32,
        ),
    }
}
