use crate::{
    ctypes::c_void, define_crankstart_api, playdate_sprite, LCDBitmap, LCDBitmapDrawMode,
    LCDBitmapFlip, LCDRect, LCDSprite, LCDSpriteCollisionFilterProc, LCDSpriteDrawFunction,
    LCDSpriteUpdateFunction, PDRect, SpriteCollisionInfo, SpriteQueryInfo,
};

define_crankstart_api! {
    #[allow(dead_code)]
    pub(crate) struct SpriteAPI => playdate_sprite {
        ; // No sub-API fields
        pub setAlwaysRedraw: unsafe extern "C" fn(flag: i32),
        pub addDirtyRect: unsafe extern "C" fn(dirtyRect: LCDRect),
        pub drawSprites: unsafe extern "C" fn(),
        pub updateAndDrawSprites: unsafe extern "C" fn(),
        pub newSprite: unsafe extern "C" fn() -> *mut LCDSprite,
        pub freeSprite: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub copy: unsafe extern "C" fn(sprite: *mut LCDSprite) -> *mut LCDSprite,
        pub addSprite: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub removeSprite: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub removeSprites: unsafe extern "C" fn(sprites: *mut *mut LCDSprite, count: i32),
        pub removeAllSprites: unsafe extern "C" fn(),
        pub getSpriteCount: unsafe extern "C" fn() -> i32,
        pub setBounds: unsafe extern "C" fn(sprite: *mut LCDSprite, bounds: PDRect),
        pub getBounds: unsafe extern "C" fn(sprite: *mut LCDSprite) -> PDRect,
        pub moveTo: unsafe extern "C" fn(sprite: *mut LCDSprite, x: f32, y: f32),
        pub moveBy: unsafe extern "C" fn(sprite: *mut LCDSprite, dx: f32, dy: f32),
        pub setImage: unsafe extern "C" fn(
            sprite: *mut LCDSprite,
            image: *mut LCDBitmap,
            flip: LCDBitmapFlip,
        ),
        pub getImage: unsafe extern "C" fn(sprite: *mut LCDSprite) -> *mut LCDBitmap,
        pub setSize: unsafe extern "C" fn(s: *mut LCDSprite, width: f32, height: f32),
        pub setZIndex: unsafe extern "C" fn(sprite: *mut LCDSprite, zIndex: i16),
        pub getZIndex: unsafe extern "C" fn(sprite: *mut LCDSprite) -> i16,
        pub setDrawMode: unsafe extern "C" fn(sprite: *mut LCDSprite, mode: LCDBitmapDrawMode),
        pub setImageFlip: unsafe extern "C" fn(sprite: *mut LCDSprite, flip: LCDBitmapFlip),
        pub getImageFlip: unsafe extern "C" fn(sprite: *mut LCDSprite) -> LCDBitmapFlip,
        pub setStencil: unsafe extern "C" fn(sprite: *mut LCDSprite, stencil: *mut LCDBitmap),
        pub setClipRect: unsafe extern "C" fn(sprite: *mut LCDSprite, clipRect: LCDRect),
        pub clearClipRect: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub setClipRectsInRange:
            unsafe extern "C" fn(clipRect: LCDRect, startZ: i32, endZ: i32),
        pub clearClipRectsInRange: unsafe extern "C" fn(startZ: i32, endZ: i32),
        pub setUpdatesEnabled: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub updatesEnabled: unsafe extern "C" fn(sprite: *mut LCDSprite) -> i32,
        pub setCollisionsEnabled: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub collisionsEnabled: unsafe extern "C" fn(sprite: *mut LCDSprite) -> i32,
        pub setVisible: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub isVisible: unsafe extern "C" fn(sprite: *mut LCDSprite) -> i32,
        pub setOpaque: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub markDirty: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub setTag: unsafe extern "C" fn(sprite: *mut LCDSprite, tag: u8),
        pub getTag: unsafe extern "C" fn(sprite: *mut LCDSprite) -> u8,
        pub setIgnoresDrawOffset: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub setUpdateFunction:
            unsafe extern "C" fn(sprite: *mut LCDSprite, func: LCDSpriteUpdateFunction),
        pub setDrawFunction:
            unsafe extern "C" fn(sprite: *mut LCDSprite, func: LCDSpriteDrawFunction),
        pub getPosition: unsafe extern "C" fn(sprite: *mut LCDSprite, x: *mut f32, y: *mut f32),
        pub resetCollisionWorld: unsafe extern "C" fn(),
        pub setCollideRect: unsafe extern "C" fn(sprite: *mut LCDSprite, collideRect: PDRect),
        pub getCollideRect: unsafe extern "C" fn(sprite: *mut LCDSprite) -> PDRect,
        pub clearCollideRect: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub setCollisionResponseFunction:
            unsafe extern "C" fn(sprite: *mut LCDSprite, func: LCDSpriteCollisionFilterProc),
        pub checkCollisions: unsafe extern "C" fn(
            sprite: *mut LCDSprite,
            goalX: f32,
            goalY: f32,
            actualX: *mut f32,
            actualY: *mut f32,
            len: *mut i32,
        ) -> *mut SpriteCollisionInfo,
        pub moveWithCollisions: unsafe extern "C" fn(
            sprite: *mut LCDSprite,
            goalX: f32,
            goalY: f32,
            actualX: *mut f32,
            actualY: *mut f32,
            len: *mut i32,
        ) -> *mut SpriteCollisionInfo,
        pub querySpritesAtPoint:
            unsafe extern "C" fn(x: f32, y: f32, len: *mut i32) -> *mut *mut LCDSprite,
        pub querySpritesInRect: unsafe extern "C" fn(
            x: f32,
            y: f32,
            width: f32,
            height: f32,
            len: *mut i32,
        ) -> *mut *mut LCDSprite,
        pub querySpritesAlongLine: unsafe extern "C" fn(
            x1: f32,
            y1: f32,
            x2: f32,
            y2: f32,
            len: *mut i32,
        ) -> *mut *mut LCDSprite,
        pub querySpriteInfoAlongLine: unsafe extern "C" fn(
            x1: f32,
            y1: f32,
            x2: f32,
            y2: f32,
            len: *mut i32,
        ) -> *mut SpriteQueryInfo,
        pub overlappingSprites: unsafe extern "C" fn(
            sprite: *mut LCDSprite,
            len: *mut i32,
        ) -> *mut *mut LCDSprite,
        pub allOverlappingSprites: unsafe extern "C" fn(len: *mut i32) -> *mut *mut LCDSprite,
        pub setStencilPattern: unsafe extern "C" fn(sprite: *mut LCDSprite, pattern: *mut u8),
        pub clearStencil: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub setUserdata:  unsafe extern "C" fn(sprite: *mut LCDSprite, userdata: *mut c_void),
        pub getUserdata: unsafe extern "C" fn(sprite: *mut LCDSprite) -> *mut c_void,
        pub setStencilImage:
            unsafe extern "C" fn(sprite: *mut LCDSprite, stencil: *mut LCDBitmap, tile: i32),
        pub setCenter: unsafe extern "C" fn(s: *mut LCDSprite, x: f32, y: f32),
        pub getCenter: unsafe extern "C" fn(s: *mut LCDSprite, x: *mut f32, y: *mut f32),
    }
}
