use {
    self::video::VideoAPI,
    crate::{
        define_crankstart_api,
        pd_api::{
            ctypes::{c_char, c_void},
            playdate_graphics, LCDBitmap, LCDBitmapDrawMode, LCDBitmapFlip, LCDBitmapTable,
            LCDColor, LCDFont, LCDFontData, LCDFontGlyph, LCDFontPage, LCDLineCapStyle,
            LCDPolygonFillRule, LCDRect, LCDSolidColor, PDStringEncoding,
        },
    },
};

pub mod video;

define_crankstart_api! {
    pub struct GraphicsAPI => playdate_graphics {
        pub video: VideoAPI;
        pub(crate) clear: unsafe extern "C" fn(color: LCDColor),
        pub(crate) setBackgroundColor: unsafe extern "C" fn(color: LCDSolidColor),
        pub(crate) setStencil: unsafe extern "C" fn(stencil: *mut LCDBitmap),
        pub(crate) setDrawMode: unsafe extern "C" fn(mode: LCDBitmapDrawMode) -> LCDBitmapDrawMode,
        pub(crate) setDrawOffset: unsafe extern "C" fn(dx: i32, dy: i32),
        pub(crate) setClipRect: unsafe extern "C" fn(x: i32, y: i32, width: i32, height: i32),
        pub(crate) clearClipRect: unsafe extern "C" fn(),
        pub(crate) setLineCapStyle: unsafe extern "C" fn(endCapStyle: LCDLineCapStyle),
        pub(crate) setFont: unsafe extern "C" fn(font: *mut LCDFont),
        pub(crate) setTextTracking: unsafe extern "C" fn(tracking: i32),
        pub(crate) pushContext: unsafe extern "C" fn(target: *mut LCDBitmap),
        pub(crate) popContext: unsafe extern "C" fn(),
        pub(crate) drawBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
            flip: LCDBitmapFlip,
        ),
        pub(crate) tileBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            flip: LCDBitmapFlip,
        ),
        pub(crate) drawLine: unsafe extern "C" fn(
            x1: i32,
            y1: i32,
            x2: i32,
            y2: i32,
            width: i32,
            color: LCDColor,
        ),
        pub(crate) fillTriangle: unsafe extern "C" fn(
            x1: i32,
            y1: i32,
            x2: i32,
            y2: i32,
            x3: i32,
            y3: i32,
            color: LCDColor,
        ),
        pub(crate) drawRect: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            color: LCDColor,
        ),
        pub(crate) fillRect: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            color: LCDColor,
        ),
        pub(crate) drawEllipse: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            lineWidth: i32,
            startAngle: f32,
            endAngle: f32,
            color: LCDColor,
        ),
        pub(crate) fillEllipse: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
            startAngle: f32,
            endAngle: f32,
            color: LCDColor,
        ),
        pub(crate) drawScaledBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
            xscale: f32,
            yscale: f32,
        ),
        pub(crate) drawText: unsafe extern "C" fn(
            text: *const c_void,
            len: usize,
            encoding: PDStringEncoding,
            x: i32,
            y: i32,
        ) -> i32,
        pub(crate) newBitmap: unsafe extern "C" fn(
            width: i32,
            height: i32,
            bgcolor: LCDColor,
        ) -> *mut LCDBitmap,
        pub(crate) freeBitmap: unsafe extern "C" fn(arg1: *mut LCDBitmap),
        pub(crate) loadBitmap: unsafe extern "C" fn(
            path: *const c_char,
            outerr: *mut *const c_char,
        ) -> *mut LCDBitmap,
        pub(crate) copyBitmap: unsafe extern "C" fn(bitmap: *mut LCDBitmap) -> *mut LCDBitmap,
        pub(crate) loadIntoBitmap: unsafe extern "C" fn(
            path: *const c_char,
            bitmap: *mut LCDBitmap,
            outerr: *mut *const c_char,
        ),
        pub(crate) getBitmapData: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            width: *mut i32,
            height: *mut i32,
            rowbytes: *mut i32,
            mask: *mut *mut u8,
            data: *mut *mut u8,
        ),
        pub(crate) clearBitmap: unsafe extern "C" fn(bitmap: *mut LCDBitmap, bgcolor: LCDColor),
        pub(crate) rotatedBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            rotation: f32,
            xscale: f32,
            yscale: f32,
            allocedSize: *mut i32,
        ) -> *mut LCDBitmap,
        pub(crate) newBitmapTable: unsafe extern "C" fn(
            count: i32,
            width: i32,
            height: i32,
        ) -> *mut LCDBitmapTable,
        pub(crate) freeBitmapTable: unsafe extern "C" fn(table: *mut LCDBitmapTable),
        pub(crate) loadBitmapTable: unsafe extern "C" fn(
            path: *const c_char,
            outerr: *mut *const c_char,
        ) -> *mut LCDBitmapTable,
        pub(crate) loadIntoBitmapTable: unsafe extern "C" fn(
            path: *const c_char,
            table: *mut LCDBitmapTable,
            outerr: *mut *const c_char,
        ),
        pub(crate) getTableBitmap:
            unsafe extern "C" fn(table: *mut LCDBitmapTable, idx: i32) -> *mut LCDBitmap,
        pub(crate) loadFont: unsafe extern "C" fn(
            path: *const c_char,
            outErr: *mut *const c_char,
        ) -> *mut LCDFont,
        pub(crate) getFontPage:
            unsafe extern "C" fn(font: *mut LCDFont, c: u32) -> *mut LCDFontPage,
        pub(crate) getPageGlyph: unsafe extern "C" fn(
            page: *mut LCDFontPage,
            c: u32,
            bitmap: *mut *mut LCDBitmap,
            advance: *mut i32,
        ) -> *mut LCDFontGlyph,
        pub(crate) getGlyphKerning: unsafe extern "C" fn(
            glyph: *mut LCDFontGlyph,
            glyphcode: u32,
            nextcode: u32,
        ) -> i32,
        pub(crate) getTextWidth: unsafe extern "C" fn(
            font: *mut LCDFont,
            text: *const c_void,
            len: usize,
            encoding: PDStringEncoding,
            tracking: i32,
        ) -> i32,
        pub(crate) getFrame: unsafe extern "C" fn() -> *mut u8,
        pub(crate) getDisplayFrame: unsafe extern "C" fn() -> *mut u8,
        pub(crate) getDebugBitmap: unsafe extern "C" fn() -> *mut LCDBitmap,
        pub(crate) copyFrameBufferBitmap: unsafe extern "C" fn() -> *mut LCDBitmap,
        pub(crate) markUpdatedRows: unsafe extern "C" fn(start: i32, end: i32),
        pub(crate) display: unsafe extern "C" fn(),
        pub(crate) setColorToPattern: unsafe extern "C" fn(
            color: *mut LCDColor,
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
        ),
        pub(crate) checkMaskCollision: unsafe extern "C" fn(
            bitmap1: *mut LCDBitmap,
            x1: i32,
            y1: i32,
            flip1: LCDBitmapFlip,
            bitmap2: *mut LCDBitmap,
            x2: i32,
            y2: i32,
            flip2: LCDBitmapFlip,
            rect: LCDRect,
        ) -> i32,
        pub(crate) setScreenClipRect: unsafe extern "C" fn(
            x: i32,
            y: i32,
            width: i32,
            height: i32,
        ),
        pub(crate) fillPolygon: unsafe extern "C" fn(
            nPoints: i32,
            coords: *mut i32,
            color: LCDColor,
            fillrule: LCDPolygonFillRule,
        ),
        pub(crate) getFontHeight: unsafe extern "C" fn(font: *mut LCDFont) -> u8,
        pub(crate) getDisplayBufferBitmap: unsafe extern "C" fn() -> *mut LCDBitmap,
        pub(crate) drawRotatedBitmap: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
            rotation: f32,
            centerx: f32,
            centery: f32,
            xscale: f32,
            yscale: f32,
        ),
        pub(crate) setTextLeading: unsafe extern "C" fn(lineHeightAdustment: i32),
        pub(crate) setBitmapMask:
            unsafe extern "C" fn(bitmap: *mut LCDBitmap, mask: *mut LCDBitmap) -> i32,
        pub(crate) getBitmapMask: unsafe extern "C" fn(bitmap: *mut LCDBitmap) -> *mut LCDBitmap,
        pub(crate) setStencilImage: unsafe extern "C" fn(stencil: *mut LCDBitmap, tile: i32),
        pub(crate) makeFontFromData:
            unsafe extern "C" fn(data: *mut LCDFontData, wide: i32) -> *mut LCDFont,
        pub(crate) getTextTracking: unsafe extern "C" fn() -> i32,
        pub(crate) setPixel: unsafe extern "C" fn(x: i32, y: i32, c: LCDColor),
        pub(crate) getBitmapPixel: unsafe extern "C" fn(
            bitmap: *mut LCDBitmap,
            x: i32,
            y: i32,
        ) -> LCDSolidColor,
        pub(crate) getBitmapTableInfo: unsafe extern "C" fn(
            table: *mut LCDBitmapTable,
            count: *mut i32,
            width: *mut i32,
        ),
    }
}
