use crate::{
    define_crankstart_api,
    pd_api::{
        ctypes::c_void, playdate_sprite, LCDBitmap, LCDBitmapDrawMode, LCDBitmapFlip, LCDRect,
        LCDSprite, LCDSpriteCollisionFilterProc, LCDSpriteDrawFunction, LCDSpriteUpdateFunction,
        PDRect, SpriteCollisionInfo, SpriteQueryInfo,
    },
};

define_crankstart_api! {
    pub struct SpriteAPI => playdate_sprite {
        ; // No sub-API fields
        pub(crate) setAlwaysRedraw: unsafe extern "C" fn(flag: i32),
        pub(crate) addDirtyRect: unsafe extern "C" fn(dirtyRect: LCDRect),
        pub(crate) drawSprites: unsafe extern "C" fn(),
        pub(crate) updateAndDrawSprites: unsafe extern "C" fn(),
        pub(crate) newSprite: unsafe extern "C" fn() -> *mut LCDSprite,
        pub(crate) freeSprite: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub(crate) copy: unsafe extern "C" fn(sprite: *mut LCDSprite) -> *mut LCDSprite,
        pub(crate) addSprite: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub(crate) removeSprite: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub(crate) removeSprites: unsafe extern "C" fn(sprites: *mut *mut LCDSprite, count: i32),
        pub(crate) removeAllSprites: unsafe extern "C" fn(),
        pub(crate) getSpriteCount: unsafe extern "C" fn() -> i32,
        pub(crate) setBounds: unsafe extern "C" fn(sprite: *mut LCDSprite, bounds: PDRect),
        pub(crate) getBounds: unsafe extern "C" fn(sprite: *mut LCDSprite) -> PDRect,
        pub(crate) moveTo: unsafe extern "C" fn(sprite: *mut LCDSprite, x: f32, y: f32),
        pub(crate) moveBy: unsafe extern "C" fn(sprite: *mut LCDSprite, dx: f32, dy: f32),
        pub(crate) setImage: unsafe extern "C" fn(
            sprite: *mut LCDSprite,
            image: *mut LCDBitmap,
            flip: LCDBitmapFlip,
        ),
        pub(crate) getImage: unsafe extern "C" fn(sprite: *mut LCDSprite) -> *mut LCDBitmap,
        pub(crate) setSize: unsafe extern "C" fn(s: *mut LCDSprite, width: f32, height: f32),
        pub(crate) setZIndex: unsafe extern "C" fn(sprite: *mut LCDSprite, zIndex: i16),
        pub(crate) getZIndex: unsafe extern "C" fn(sprite: *mut LCDSprite) -> i16,
        pub(crate) setDrawMode: unsafe extern "C" fn(sprite: *mut LCDSprite, mode: LCDBitmapDrawMode),
        pub(crate) setImageFlip: unsafe extern "C" fn(sprite: *mut LCDSprite, flip: LCDBitmapFlip),
        pub(crate) getImageFlip: unsafe extern "C" fn(sprite: *mut LCDSprite) -> LCDBitmapFlip,
        pub(crate) setStencil: unsafe extern "C" fn(sprite: *mut LCDSprite, stencil: *mut LCDBitmap),
        pub(crate) setClipRect: unsafe extern "C" fn(sprite: *mut LCDSprite, clipRect: LCDRect),
        pub(crate) clearClipRect: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub(crate) setClipRectsInRange:
            unsafe extern "C" fn(clipRect: LCDRect, startZ: i32, endZ: i32),
        pub(crate) clearClipRectsInRange: unsafe extern "C" fn(startZ: i32, endZ: i32),
        pub(crate) setUpdatesEnabled: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub(crate) updatesEnabled: unsafe extern "C" fn(sprite: *mut LCDSprite) -> i32,
        pub(crate) setCollisionsEnabled: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub(crate) collisionsEnabled: unsafe extern "C" fn(sprite: *mut LCDSprite) -> i32,
        pub(crate) setVisible: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub(crate) isVisible: unsafe extern "C" fn(sprite: *mut LCDSprite) -> i32,
        pub(crate) setOpaque: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub(crate) markDirty: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub(crate) setTag: unsafe extern "C" fn(sprite: *mut LCDSprite, tag: u8),
        pub(crate) getTag: unsafe extern "C" fn(sprite: *mut LCDSprite) -> u8,
        pub(crate) setIgnoresDrawOffset: unsafe extern "C" fn(sprite: *mut LCDSprite, flag: i32),
        pub(crate) setUpdateFunction:
            unsafe extern "C" fn(sprite: *mut LCDSprite, func: LCDSpriteUpdateFunction),
        pub(crate) setDrawFunction:
            unsafe extern "C" fn(sprite: *mut LCDSprite, func: LCDSpriteDrawFunction),
        pub(crate) getPosition: unsafe extern "C" fn(sprite: *mut LCDSprite, x: *mut f32, y: *mut f32),
        pub(crate) resetCollisionWorld: unsafe extern "C" fn(),
        pub(crate) setCollideRect: unsafe extern "C" fn(sprite: *mut LCDSprite, collideRect: PDRect),
        pub(crate) getCollideRect: unsafe extern "C" fn(sprite: *mut LCDSprite) -> PDRect,
        pub(crate) clearCollideRect: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub(crate) setCollisionResponseFunction:
            unsafe extern "C" fn(sprite: *mut LCDSprite, func: LCDSpriteCollisionFilterProc),
        pub(crate) checkCollisions: unsafe extern "C" fn(
            sprite: *mut LCDSprite,
            goalX: f32,
            goalY: f32,
            actualX: *mut f32,
            actualY: *mut f32,
            len: *mut i32,
        ) -> *mut SpriteCollisionInfo,
        pub(crate) moveWithCollisions: unsafe extern "C" fn(
            sprite: *mut LCDSprite,
            goalX: f32,
            goalY: f32,
            actualX: *mut f32,
            actualY: *mut f32,
            len: *mut i32,
        ) -> *mut SpriteCollisionInfo,
        pub(crate) querySpritesAtPoint:
            unsafe extern "C" fn(x: f32, y: f32, len: *mut i32) -> *mut *mut LCDSprite,
        pub(crate) querySpritesInRect: unsafe extern "C" fn(
            x: f32,
            y: f32,
            width: f32,
            height: f32,
            len: *mut i32,
        ) -> *mut *mut LCDSprite,
        pub(crate) querySpritesAlongLine: unsafe extern "C" fn(
            x1: f32,
            y1: f32,
            x2: f32,
            y2: f32,
            len: *mut i32,
        ) -> *mut *mut LCDSprite,
        pub(crate) querySpriteInfoAlongLine: unsafe extern "C" fn(
            x1: f32,
            y1: f32,
            x2: f32,
            y2: f32,
            len: *mut i32,
        ) -> *mut SpriteQueryInfo,
        pub(crate) overlappingSprites: unsafe extern "C" fn(
            sprite: *mut LCDSprite,
            len: *mut i32,
        ) -> *mut *mut LCDSprite,
        pub(crate) allOverlappingSprites: unsafe extern "C" fn(len: *mut i32) -> *mut *mut LCDSprite,
        pub(crate) setStencilPattern: unsafe extern "C" fn(sprite: *mut LCDSprite, pattern: *mut u8),
        pub(crate) clearStencil: unsafe extern "C" fn(sprite: *mut LCDSprite),
        pub(crate) setUserdata:  unsafe extern "C" fn(sprite: *mut LCDSprite, userdata: *mut c_void),
        pub(crate) getUserdata: unsafe extern "C" fn(sprite: *mut LCDSprite) -> *mut c_void,
        pub(crate) setStencilImage:
            unsafe extern "C" fn(sprite: *mut LCDSprite, stencil: *mut LCDBitmap, tile: i32),
        pub(crate) setCenter: unsafe extern "C" fn(s: *mut LCDSprite, x: f32, y: f32),
        pub(crate) getCenter: unsafe extern "C" fn(s: *mut LCDSprite, x: *mut f32, y: *mut f32),
    }
}
